name: CI

on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run format && pnpm run typecheck && pnpm run build
